<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crystals.Core\Crystals.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="WPF-UI.Tray" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\icon.png" />
    <Resource Include="Resources\icon.png" />
    <None Remove="Resources\Sources\MusicSource.png" />
    <Resource Include="Resources\Sources\MusicSource.png" />
  </ItemGroup>

</Project>
