<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crystals.Core\Crystals.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="WPF-UI.Tray" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Sources\MusicSource.png" />
    <None Remove="Resources\Icon.png" />
    <None Remove="Resources\Sources\Default.png" />
    <None Remove="Resources\Sources\Music.png" />
    <Resource Include="Resources\Sources\Music.png" />
    <None Remove="Resources\Devices\Arduino.png" />
    <Resource Include="Resources\Devices\Arduino.png" />
    <None Remove="Resources\Devices\Keyboard.png" />
    <Resource Include="Resources\Devices\Keyboard.png" />
    <None Remove="Resources\Ok.png" />
    <Resource Include="Resources\Ok.png" />
    <None Remove="Resources\Icons\AE.png" />
    <Resource Include="Resources\Icons\AE.png" />
    <None Remove="Resources\Icons\Crystals.png" />
    <Resource Include="Resources\Icons\Crystals.png" />
    <None Remove="Resources\Icons\Crystals80.png" />
    <None Remove="Resources\Reset.png" />
    <Resource Include="Resources\Reset.png" />
    <None Remove="Resources\Error.png" />
    <Resource Include="Resources\Error.png" />
    <None Remove="Resources\Save.png" />
    <Resource Include="Resources\Save.png" />
  </ItemGroup>

</Project>
